# Generated by Django 3.1.2 on 2020-10-23 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, verbose_name='Employee ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('designation', models.CharField(choices=[('AD', 'Administrator'), ('MG', 'Manager'), ('AC', 'Accountant')], max_length=50)),
                ('phone', models.CharField(max_length=14, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(default='media/default_user.png', upload_to='customer_pics', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='', max_length=1000)),
                ('phone', models.CharField(max_length=14, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(default='media/default_user.png', upload_to='customer_pics', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
