# Generated by Django 3.1.2 on 2020-10-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='designation',
        ),
    ]
