# Generated by Django 3.1.2 on 2020-10-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('SZ', 'Sizzlers'), ('PS', 'Pasta'), ('AP', 'Appetizers'), ('PZ', 'Pizzas'), ('DS', 'Desserts'), ('BV', 'Beverages')], max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_non_veg', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('image', models.ImageField(default='media/default_item.png', upload_to='item_pics', verbose_name='Feature Image')),
                ('non_availablity_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='items.item')),
                ('item2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='items.item')),
                ('item3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item3', to='items.item')),
                ('item4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item4', to='items.item')),
                ('item5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item5', to='items.item')),
            ],
        ),
    ]
