# Generated by Django 3.1.2 on 2020-10-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20201024_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='combo',
            name='image',
            field=models.ImageField(default='media/default_item.png', upload_to='item_pics', verbose_name='Feature Image'),
        ),
        migrations.AddField(
            model_name='combo',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='combo',
            name='non_availablity_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
    ]
