# Generated by Django 3.1.2 on 2020-10-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20201024_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='non_availablity_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
