# Generated by Django 3.1.2 on 2020-10-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20201028_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='non_availablity_time',
        ),
    ]
