# Generated by Django 3.1.2 on 2020-10-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_placed',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='time_placed',
            field=models.TimeField(default=None),
        ),
    ]
