# Generated by Django 3.1.2 on 2020-10-29 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201029_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(default=datetime.date(2020, 10, 29)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_placed',
            field=models.TimeField(default=datetime.datetime(2020, 10, 29, 20, 56, 5, 844857)),
        ),
    ]
